Fixes discarding host events when from_q queue is None
This is a grave bug because every time ask_reinit() is called from create_message() and self.from_q is None, the complete message is discarded due a captured Exception.

```
2014-09-26 14:18:39,417 [1411733919] Error :   [broker-master] [Canopsis] Error: there was an error while trying to create message for host
2014-09-26 14:18:39,417 [1411733919] Error :   [broker-master] [Canopsis] Error: 'NoneType' object has no attribute 'put'
```